### PR TITLE
fix TBB detection

### PR DESCRIPTION
**Pull request by mboisson**
Fixes issue https://github.com/woodem/woo/issues/33

### CODE REVIEW

**Comment by eudoxos** [comment]
This fails [in the CI]((https://github.com/woodem/woo/runs/3346948141) and also when I run it locally. It fixes TBB but breaks other things. Why not just add e.g.
```cmake
list(INSERT CMAKE_MODULE_PATH 0 "${CMAKE_CURRENT_SOURCE_DIR}")
```
without moving fiels around? One can also do `cmake -DCMAKE_MODULE_PATH=/some/path` (IIRC) to set the extra path from the command-line, w/o modifying `CMakeLists.txt`.

**Comment by eudoxos** [comment]
PS I am going to be offline for next 2 weeks, so will only react afterwards.

**Comment by mboisson** [comment]
Yes, I guess we can keep them in the root directory, although it is, in my opinion, bad practice.

**Comment by eudoxos** [comment]
Hi, thank you for the effort about this improvement; I did as you suggested (move files to `cmake/`) in 343f35474 and also found out why the TBB detection was not working for you - the current (`.`, now `cmake/`) directory was not added to cmake module path until *after* TBB detection (later down in the file), this should be fixed now. Thank you helping to make Woo more straightforward to install.

**Pull request closed without merging**
