### PR TITLE
Renamed buoyancy, added basic formula for buoyancy without water drag

### PR DESCRIPTION
**Pull request by sjl767**
Left out water drag as I thought it would be good to be able to choose whether water drag is present or have pure buoyancy. Unsure whether to add water drag as another Engines subclass or to have it be an option in water drag.

### CODE REVIEW

**Comment by eudoxos** [comment]
I'd add drag as parameters to this engine. I imagine people using drag will also usually want to have buoyancy. Look at the https://woodem.org/prog/index.html for documentation on class attributes. (

**Comment by sjl767** [comment]
Added most of the functionality (undocumented as of yet). However, in my test case (the MWE I sent you to test the memory leak previously), it appears that the gravity engine overrides any effect of HalfspaceBuoyancy(). With a non-zero gravity vector, the freefall velocity of the particles are always the same (~-37 in the z direction) regardless of whether HalfspaceBuoyancy() is a member of engines. I confirmed that applying any sort of force through HB() when gravity is zero works. Unsure how to proceed.

**Comment by eudoxos** [comment]
Maybe a better approach would be to use DemField.gravity also to determine "downwards" direction, and only set a single point which will define the liquid surface (gravity being normal to it)? It could simplify the usage (less likely to mess up and have gravity pointing somewhere else).

I will try to comment the rest in the code (never done that, but I think it is possible)

**Comment by sjl767** [comment]
Updated the equations based on the paper I found. Only thing is it doesn't account for partially submerged situations at the moment. In any case, [gravity still overrides any effect](https://github.com/woodem/woo/pull/17#issuecomment-143195175). Thank you for the help so far, please let me know what's the next step.

**Comment by eudoxos** [comment]
I did the pull request but it is the old code which got pulled. Did youo forget to push your recent changes? I am not sure how this works, maybe you need to update the pull request as well?

**Comment by sjl767** [comment]
I fixed a small error and made a new pull request. Hopefully that will enable the latest commit to be merged.

**Pull request merged**
